# -*- coding: utf-8 -*-
"""Task 1| Hangman game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imrVkEFNVLF9-IAplhLvvQi9QoDj32m4
"""

#===================================================================
#               TASK 1 : HAMGMAN GAME
#===================================================================

"""
Summary
A simple text based hangman game where the player guesses a word one latter at a time

Key Concepts
  * random.choice() to pick a random word
  * while loop for game loop
  * if-else to check correct/incorrect guess
  * lisy & string manipulation
"""

import random

#Predifind word list
words = ["python", "hangman", "computer", "developer", "letter"]

#Chose a random word
word = random.choice(words)
guessed = ["_"]*len(word)
attempts = 6
guessed_letters = []

print("================ Welcome to Hangman! ===================")
print("".join(guessed))
print("========================================================")

while attempts > 0:
  guess = input("Guess a letter: ").lower()

  if guess in guessed_letters:
    print("You already guessed that letter. Try again.")
    continue

  guessed_letters.append(guess)

  if guess in word:
    print("Correct guess!")
    for i in range(len(word)):
      if word[i] == guess:
        guessed[i] = guess
  else:
    attempts -= 1
    print(f"Incorrect guess. You have {attempts} attempts left.")

  print("".join(guessed))
  print("========================================================")

  if "_" not in guessed:
    print("Congratulations! You guessed the word correctly:", word)
    break

if attempts == 0:
  print(f"Sorry, you ran out of attempts. The word was {word}.")
  print("========================================================")

else:
  print("\n================ Thank you for playing Hangman! ====================")